export const ADD_FAVOURITE = 'ADD_FAVOURITE'
export const SET_RECOMMENDATIONS = 'SET_RECOMMENDATIONS'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_IS_LOADING = 'SET_IS_LOADING'

// CART
export const SET_IS_CART_FILLED = 'SET_IS_CART_FILLED'
export const SET_INSIDE_CART = 'SET_INSIDE_CART'
export const SET_TOTAL_PRICE_IN_CART = 'SET_TOTAL_PRICE_IN_CART'

export const SET_CUSTOMER_INFO = 'SET_CUSTOMER_INFO'
export const SET_ORDER_BY_TYPE = 'SET_ORDER_BY_TYPE'
export const ORDER_DETAIL = 'ORDER_DETAIL'
export const SET_COOKIE = 'SET_COOKIE'

export const SET_PRODUCT_TO_SHOW = 'SET_PRODUCT_TO_SHOW'
export const SET_COMPLETE_PRODUCT = 'SET_COMPLETE_PRODUCT'
export const SET_PRODUCT_BY_CATEGORY = 'SET_PRODUCT_BY_CATEGORY'
export const SET_LIST_CATEGORY = 'SET_LIST_CATEGORY'
export const SET_CART_STEP = 'SET_CART_STEP'